# -*- coding: utf-8 -*-
"""wynagrodzenia_prognoza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UOUogOLDOBc4C6h3MtWUt0prJvT-N0zD
"""



import pandas as pd

df = pd.read_excel("Prognozy_Baza_Danych.xlsx", sheet_name=0)
df = df.rename(columns={'Zmienna': 'Data'})[['Data', 'Wynagrodzenia']]
df = df[(df['Data'] >= '2015 M02') & (df['Data'] <= '2018 M08')]
df.iloc[-3:, df.columns.get_loc('Wynagrodzenia')] = pd.NA

pd.set_option('display.max_rows', None)
display(df)

import numpy as np
from sklearn.linear_model import LinearRegression

df_model = df.copy()
df_model['Trend'] = np.arange(len(df_model))

df_model['grudzień'] = df_model['Data'].str.contains('M12').astype(int)

train_df = df_model.dropna(subset=['Wynagrodzenia'])
predict_df = df_model[df_model['Wynagrodzenia'].isna()]

features = ['Trend', 'grudzień']
X_train = train_df[features]
y_train = train_df['Wynagrodzenia']

model = LinearRegression()
model.fit(X_train, y_train)

df_model['Prognoza_Model'] = model.predict(df_model[features])
display(df_model[['Data', 'Wynagrodzenia', 'grudzień', 'Prognoza_Model']])

import statsmodels.api as sm
import statsmodels.stats.diagnostic as dg
from statsmodels.stats.stattools import jarque_bera

X_train_sm = sm.add_constant(X_train.astype(float))

model_sm = sm.OLS(y_train, X_train_sm).fit()

print(model_sm.summary())

from statsmodels.tsa.holtwinters import Holt

# 1. Przygotowanie szeregu czasowego
train_series = df.dropna(subset=['Wynagrodzenia'])['Wynagrodzenia']

# 2. Dopasowanie modelu Holta (Linear Trend)
holt_model_fit = Holt(train_series, exponential=False, damped_trend=False).fit()

# 3. Wygenerowanie prognoz wygasłych (fitted values) i prognozy ex-ante
fitted_values = holt_model_fit.fittedvalues
forecast_steps = 3
holt_forecast = holt_model_fit.forecast(forecast_steps)

# 4. Przygotowanie pełnej tabeli z wynikami
df_holt = df_model[['Data', 'Wynagrodzenia']].copy()
df_holt['Prognoza_Holta_Wygasła'] = pd.Series(fitted_values)
# Corrected: Assign holt_forecast to the last 'forecast_steps' rows of df_holt using their actual index labels
df_holt.loc[df_holt.index[-forecast_steps:], 'Prognoza_Holta_Ex-Ante'] = holt_forecast.values

print("Wyniki modelu Holta (Prognozy wygasłe i ex-ante):")
display(df_holt)